FROM nginx

COPY ./etc/nginx/ssl /etc/nginx/ssl

ADD ./etc/nginx/default.conf /etc/nginx/conf.d

#openssl req -x509 -out localhost.crt -keyout localhost.key \
#  -newkey rsa:2048 -nodes -sha256 \
#  -subj '/CN=localhost' -extensions EXT -config <( \
#   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")